# Arrays

**Topics**
* Creating using List (One dimentional Array)
* multidimentional array using List of List
* Equal interval Array
* Equal Spaced Array
* Array of Ones
* Array of Zeros
* Diagonal Array With Ones
* Diagonal Array
* Combining Arrays
* Opreations
* Dot Product
* Transpose 
* Math Functions
* Indexing/Slicing
* Indexing/Slicing on Multidimentional Data
* Conditional Indexing
* Copying Data
* Iterating over Arrays
* zip to iterate over two multiple iterables

**Creating using List (One dimentional Array)**

In [7]:
#import numpy as np                       # importing numpy
mylist = [1, 2, 3]                        # creating an array using a list
x = np.array(mylist)
print x
print type(x) 
y = np.array([4, 5, 6])                    # a list can be passed directly also
print y

[1 2 3]
<type 'numpy.ndarray'>
[4 5 6]


**multidimentional array using List of List**

In [10]:
m = np.array([[7, 8, 9], [10, 11, 12]])    # to create a multidimentional array
print m
m.shape                                    # to get dimention of the array

[[ 7  8  9]
 [10 11 12]]


(2L, 3L)

**Equal interval Array**

In [11]:
n = np.arange(0, 30, 2)      # start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [12]:
n = n.reshape(3, 5)          # reshape array to be 3x5
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

**Equal Spaced Array**

In [13]:
o = np.linspace(0, 4, 9)      # return 9 evenly spaced values from 0 to 4
o

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

In [14]:
o.resize(3, 3)
o

array([[ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ]])

**Array of Ones**

In [15]:
np.ones((3, 2))               # ones returns a new array of given shape and type, filled with ones.

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

**Array of Zeros**

In [16]:
np.zeros((2, 3))              # zeros returns a new array of given shape and type, filled with zeros.

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

**Diagonal Array With Ones**

In [17]:
np.eye(3)                      #eye returns a 2-D array with ones on the diagonal and zeros elsewhere.

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

**Diagonal Array**

In [18]:
np.diag(y)                     # diag extracts a diagonal or constructs a diagonal array.

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [19]:
np.array([1, 2, 3] * 3)        # Create an array using repeating list (or see np.tile)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [20]:
np.repeat([1, 2, 3], 3)        # Repeat elements of an array using repeat.

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

**Combining Arrays**

In [21]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [22]:
np.vstack([p, 2*p])            # vstack : stack arrays in sequence vertically (row wise)

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [23]:
np.hstack([p, 2*p])          # hstack: stack arrays in sequence horizontally (column wise)

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

**Operations**
* **" + " , " - " , " * " , " / " , "**" **(all are done elementwise)  

In [24]:
print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]
print(x * y) # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # elementwise divison         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]
print(x**2) # elementwise power  [1 2 3] ^2 =  [1 4 9]

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0 0 0]
[1 4 9]


**Dot Product**

In [25]:
x.dot(y)     # dot product  1*4 + 2*5 + 3*6   

32

**Transpose**

In [26]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [28]:
z.T     # T is used for transpose

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [29]:
z.dtype   # to see the data type of elements

dtype('int32')

In [30]:
z = z.astype('f')  # .astype('') used to cast to specific data type
z.dtype

dtype('float32')

**Math Functions**

In [34]:
a = np.array([-4, -2, 1, 3, 5])
a.sum()
a.max()
a.min()
a.mean()
a.std()
a.argmax()   # return index of max value
a.argmin()   # return index of min value
list = [a.sum(),a.max(),a.min(),a.mean(),a.std(),a.argmax(),a.argmin()]
print list

[3, 5, -4, 0.59999999999999998, 3.2619012860600183, 4, 0]


**Indexing/Slicing**

In [35]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [38]:
# selecting using index (starts with zero)
s[0], s[4], s[-1]    # a tuple will be created by default

(0, 16, 144)

In [42]:
s[1:5]    # Selecting a range output: array([ 1,  4,  9, 16])
s[-4:]    # negative indicies to count from back output: array([ 81, 100, 121, 144])
s[-5::-2] # starting 5th element from the end, and counting backwards by 2 until the beginning of the array is reached
          # output: array([64, 36, 16,  4,  0])

array([64, 36, 16,  4,  0])

**Indexing/Slicing on Multidimentional Data**

In [55]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [44]:
# bracket notation to slice: array[row, column]
r[2, 2]         # to select specific observation, output: 14
r[3, 3:6]       # to select a range of rows or columns,  output: array([21, 22, 23])
r[:2, :-1]      # selecting all the rows up to (and not including) row 2, and all the columns up to (and not including) 
                # the last column 

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [45]:
r[2:4,2:4]

array([[14, 15],
       [20, 21]])

**Conditional Indexing**

In [57]:
r[r > 30]      # return a array of values satisfying given condition

array([31, 32, 33, 34, 35])

In [53]:
r[r > 30] = 30    # replacing all values greater than 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

**Copying Data**
* data loss is a concern hence care is required while copying 

In [58]:
r2 = r[:3,:3]     # created a slice of r 
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [59]:
r2[:] = 0         # replaced all values of r2 with 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [60]:
r                 # ideally the values of r should not change but that is not the case

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [61]:
r_copy = r.copy()           # r.copy is used to avoid any changes in original array
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [63]:
r_copy[:] = 10
print(r_copy)
print(r)           

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]
[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


**Iterating over Arrays**

In [64]:
test = np.random.randint(0, 10, (4,3))
test

array([[9, 6, 3],
       [8, 9, 8],
       [0, 3, 7],
       [6, 6, 8]])

**by Row**

In [65]:
for row in test:
    print(row)

[9 6 3]
[8 9 8]
[0 3 7]
[6 6 8]


**by index**

In [66]:
for i in range(len(test)):
    print(test[i])

[9 6 3]
[8 9 8]
[0 3 7]
[6 6 8]


**by row and index**

In [67]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

('row', 0, 'is', array([9, 6, 3]))
('row', 1, 'is', array([8, 9, 8]))
('row', 2, 'is', array([0, 3, 7]))
('row', 3, 'is', array([6, 6, 8]))


**zip to iterate over two multiple iterables**

In [68]:
test2 = test**2
test2

array([[81, 36,  9],
       [64, 81, 64],
       [ 0,  9, 49],
       [36, 36, 64]])

In [69]:
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)

(array([9, 6, 3]), '+', array([81, 36,  9]), '=', array([90, 42, 12]))
(array([8, 9, 8]), '+', array([64, 81, 64]), '=', array([72, 90, 72]))
(array([0, 3, 7]), '+', array([ 0,  9, 49]), '=', array([ 0, 12, 56]))
(array([6, 6, 8]), '+', array([36, 36, 64]), '=', array([42, 42, 72]))
